model:
  key: Compressor
  params:
    channel: 256
    k: 4096
    size: [16, 8, 4, 2, 1]
    denseNorm: false
train:
  totalStep: 200000 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
  batchSize: 4
  epoch: 2
  valFreq: 20000
  trainSet: /ssdfs/datahome/tj24011/datasets/webdataset/openimages_raw/*.tar.gz
  valSet: /ssdfs/datahome/tj24011/datasets/raw/kodak
  saveDir: /ssdfs/datahome/tj24011/workspace/McQuic/saved
  target: MsSSIM
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Adam
    params:
      lr: 8.e-5 # PSNR: 5.e-3 # don't try to tune lr, it is best
      weight_decay: 0.0
      # use_nvlamb: true
  schdr:
    # key: Placeholder
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 200000 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
      warmup_steps: 5000
      gamma: 1.0
      lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
  # hooks:
  #   - key: CodebookReassign
  #     params:
  #       freq: 10000
