model:
  key: Generator
  params:
    channel: 32
    k: [4096, 4096, 4096, 4096, 4096]
    m: [1, 1, 1, 1, 1]
    denseNorm: false
    loadFrom: compressor.ckpt
train:
  totalStep: 25000 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
  batchSize: 144
  epoch: 2
  valFreq: 2500
  trainSet: /ssdfs/datahome/tj24011/datasets/webdataset/cc3m-wds/*train*.tar
  valSet: /ssdfs/datahome/tj24011/datasets/raw/kodak
  saveDir: /ssdfs/datahome/tj24011/workspace/McQuic/generation_saved
  target: MsSSIM
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: FusedLAMB
    params:
      lr: 1.e-4 # PSNR: 5.e-3 # don't try to tune lr, it is best
      weight_decay: 0.0
      # use_nvlamb: true
  schdr:
    # key: Placeholder
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 25000 # totalimage / gpus / batchsize * epochs
      warmup_steps: 250
      gamma: 1.0
      lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
