model:
  key: Generator
  params:
    channel: 32
    k: [4096, 4096, 4096, 4096, 4096]
    m: [1, 1, 1, 1, 1]
    denseNorm: false
    loadFrom: compressor/compressor_58000.ckpt
train:
  totalStep: 20000 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
  batchSize: 24
  epoch: 2
  valFreq: 10000
  trainSet: /mnt/hdd1/zhuxiaosu/datasets/cc3m-wds/*train*.tar
  valSet: valid
  saveDir: generation_saved
  target: MsSSIM
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Adam
    params:
      lr: 5.e-4 # PSNR: 5.e-3 # don't try to tune lr, it is best
      weight_decay: 0.01
      # use_nvlamb: true
  schdr:
    # key: Placeholder
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 20000 # totalimage / gpus / batchsize * epochs
      warmup_steps: 500
      gamma: 1.0
      lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
