# migrate from neon.yaml
model:
  key: GeneratorV3SelfAttention
  params:
    channel: 256
    k: 4096
    size: [16, 8, 8, 8, 8, 4, 4, 4, 4, 2, 2, 2, 2, 1, 1, 1, 1]
    denseNorm: false
    qk_norm: true
    norm_eps: 1.e-5
    loadFrom: compressor/dynamic_20000.ckpt
train:
  totalStep: 10000 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
  batchSize: 12
  epoch: 2
  valFreq: 1000
  trainSet: /mnt/hdd1/zhuxiaosu/datasets/imagenet-1k
  valSet: valid
  saveDir: generation_saved
  target: MsSSIM
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Adam
    params:
      lr: 5.e-4 # PSNR: 5.e-3 # don't try to tune lr, it is best
      weight_decay: 0.1
      # use_nvlamb: true
  schdr:
    # key: Placeholder
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 10000 # totalimage / gpus / batchsize * epochs
      warmup_steps: 250
      gamma: 1.0
      lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
