$schema: "https://raw.githubusercontent.com/xiaosu-zhu/McQuic/main/configs/schema.json"
model:
  key: Compressor
  params:
    channel: 32
    k: [4096, 4096, 4096, 4096, 4096]
    m: [1, 1, 1, 1, 1]
train:
  totalStep: 200 # totalimage / gpus / batchsize * epochs (6354785 / 8 / 6 * 1.5)
  batchSize: 2
  epoch: 2
  valFreq: 10
  trainSet: /mnt/nfs/CMG/mcquic/
  valSet: valid
  saveDir: saved
  target: MsSSIM
  externalLib: []
    # - some/modules/to/be/registered1.py
    # - some/modules/to/be/registered2.py
  optim:
    key: Adam
    params:
      lr: 1.e-4 # PSNR: 5.e-3 # don't try to tune lr, it is best
      # weight_decay: 0.0
      # use_nvlamb: true
  schdr:
    # key: Placeholder
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 200 # totalimage / gpus / batchsize * epochs
      warmup_steps: 5
      gamma: 1.0
      lrScaleRatio: 0.0
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
  hooks:
    - key: CodebookReassign
      params:
        freq: 4000
