model:
  key: Generator
  params:
    channel: 32
    k:
    - 4096
    - 4096
    - 4096
    - 4096
    - 4096
    loadFrom: compressor.ckpt
    m:
    - 1
    - 1
    - 1
    - 1
    - 1
train:
  batchSize: 2
  epoch: 2
  externalLib: []
  gpu:
    gpus: 8
    vRam: -1
    wantsMore: false
  hooks:
  - key: CodebookReassign
    params:
      freq: 4000
  optim:
    key: Adam
    params:
      lr: 0.0001
  saveDir: generation_saved
  schdr:
    key: CosineAnnealingWarmupRestarts
    params:
      first_cycle_steps: 200
      gamma: 1.0
      lrScaleRatio: 0.0
      warmup_steps: 5
  target: MsSSIM
  totalStep: 200
  trainSet: /mnt/nfs/CMG/mcquic/
  valFreq: 10
  valSet: valid
