name: Sync to Hugging Face hub
on:
  workflow_run:
    workflows: [Bump version]
    types:
      - completed

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - name: Delay 300 seconds (wait for pypi package online)
        run: sleep 300s
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clone HF
        run: |
          git clone https://xiaosu-zhu:$HF_TOKEN@huggingface.co/spaces/xiaosu-zhu/McQuic.git hfSpace
          cp mcquic/service/stCompressService.py hfSpace/
          python ci/pre_commit/update_hf_space_require.py mcquic/__init__.py hfSpace/requirements.txt
          cd hfSpace
          git add .
          git config --global user.email "xiaosu.zhu@outlook.com"
          git config --global user.name "Xiaosu Zhu"
          git commit -m "Auto deploy"
          git push
