name: Update schema.json and docs based on mcquic.config.ConfigSchema

on:
  push:
    branches: [main]
    paths: ['mcquic/config.py']

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate schema.json
        run: |
          pip install marshmallow-jsonschema json-schema-for-humans
          python ci/pre_commit/generate_schema.py mcquic/config.py configs/schema.json configs/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update config schema and configs/README.md
