name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    paths: ['mcquic/service/stCompressService.py']

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Clone HF
        run: |
          git clone https://xiaosu-zhu:$HF_TOKEN@huggingface.co/spaces/xiaosu-zhu/McQuic.git hfSpace
          cp mcquic/service/stCompressService.py hfSpace/
          python ci/pre_commit/update_hf_space_require.py mcquic/__init__.py hfSpace/requirements.txt
          cd hfSpace
          git add .
          git config --global user.email "xiaosu.zhu@outlook.com"
          git config --global user.name "Xiaosu Zhu"
          git commit -m "Auto deploy"
          git push
