name: Auto generate stub of RANS cpp module

on:
  push:
    branches: [main]
    paths: ['third_party/CompressAI/**']

jobs:
  update-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Install dependencies
        run: |
          eval "$(conda shell.bash hook)"
          conda activate
          conda install -y python=3.9 cpuonly "torchvision>=0.12,<1" "pytorch>=1.11,<2" -c pytorch
          conda install -y "pybind11>=2.6,<3" "pip>=22" "tensorboard>=2.3,<3" "rich>=10,<11" "python-lmdb>=1.2,<2" "pyyaml>=5.4,<7" "marshmallow>=3.14,<4" "click>=8,<9" "vlutils>=0.1.22" "msgpack-python>=1,<2" packaging -c xiaosu-zhu -c conda-forge
          conda install -y pip
          pip install -e .
          pip install pybind11-stubgen
      - name: Generate python stubs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate
          pybind11-stubgen --no-setup-py mcquic.rans
          mv stubs/mcquic/rans-stubs/*.pyi mcquic/rans.pyi
          sed -i 's/: str/: bytes/g' mcquic/rans.pyi
          rm -rf stubs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update config schema and configs/README.md
